const L='1387842070604967936',A='https://api.sleeper.app/v1',PX='https://api.sleeper.app/projections/nfl/regular';
const $=id=>document.getElementById(id),num=x=>Number.isFinite(+x)?+x:0,cl=(x,a,b)=>Math.max(a,Math.min(b,x)),usd=x=>'$'+Math.round(x),pc=x=>(100*x).toFixed(1)+'%';
let S={};
async function get(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${u}`);return r.json()}
function median(a){a=[...a].sort((x,y)=>x-y);if(!a.length)return 0;let m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function pname(id){let p=S.players[id]||{};return p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||id}
function ppos(id){let p=S.players[id]||{};return p.position||(p.fantasy_positions||[])[0]||''}
function pstats(id){let x=S.proj[id]||{};return x.stats||x}
function points(id){let s=pstats(id),sc=S.league.scoring_settings||{},v=0,used=0;for(const [k,m] of Object.entries(sc)){if(typeof m==='number'&&s[k]!=null){v+=num(s[k])*m;used++}}if(used)return v;return num(s.pts_ppr??s.pts_half_ppr??s.pts_std)}
function ok(slot,p){if(slot===p)return true;if(slot==='FLEX')return ['RB','WR','TE'].includes(p);if(slot==='SUPER_FLEX')return ['QB','RB','WR','TE'].includes(p);if(slot==='REC_FLEX')return ['WR','TE'].includes(p);if(slot==='WRRB_FLEX')return ['WR','RB'].includes(p);return false}
function bestLineup(ids){let slots=(S.league.roster_positions||[]).filter(x=>!['BN','IR','TAXI'].includes(x)),pool=(ids||[]).map(String),used=new Set,total=0,picks=[];for(const slot of slots){let best,bv=-999;for(const id of pool){if(used.has(id)||!ok(slot,ppos(id)))continue;let v=points(id);if(v>bv){bv=v;best=id}}if(best){used.add(best);total+=Math.max(0,bv);picks.push(best)}}return {total,picks}}
function teamName(r){let u=S.users.find(x=>x.user_id===r.owner_id);return u?.metadata?.team_name||u?.display_name||u?.username||`Roster ${r.roster_id}`}
function faabLeft(r){return Math.max(0,num(S.league.settings?.waiver_budget||1000)-num(r.settings?.waiver_budget_used))}
function simulate(teams,n=8000){let chop=new Map(teams.map(t=>[t.id,0])),cuts=[];for(let i=0;i<n;i++){let vals=teams.map(t=>{let sd=Math.max(8,t.proj*.16),u=Math.random()||.5,v=Math.random()||.5,z=Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);return [t,t.proj+z*sd]}).sort((a,b)=>a[1]-b[1]);chop.set(vals[0][0].id,chop.get(vals[0][0].id)+1);cuts.push(vals[0][1])}return {chop,cut:median(cuts),n}}
function paidBids(){let x=[];for(const t of S.tx||[]){if(t.type!=='waiver')continue;for(const [pid,rid] of Object.entries(t.adds||{}))x.push({pid,rid:+rid,bid:num(t.settings?.waiver_bid),week:num(t.leg),status:t.status})}return x.filter(x=>x.bid>0&&(x.status==='complete'||!x.status))}
function leagueInflation(){let b=paidBids();if(b.length<3)return 1;let avg=b.reduce((s,x)=>s+x.bid,0)/b.length;return cl(avg/120,.65,1.65)}
function market(pr,pos){let early=S.week<=2?1.55:S.week<=4?1.3:1,scarcity=pos==='RB'?22:pos==='WR'?14:pos==='TE'?7:0;return cl((pr*7+scarcity)*early*leagueInflation(),1,650)}
function rec(id,me){let pr=points(id),gain=Math.max(0,bestLineup([...(me.r.players||[]),id]).total-me.proj),m=market(pr,ppos(id)),need=me.risk>.25?1.8:me.risk>.15?1.4:me.risk<.07?.68:1,value=cl((pr*4+gain*13)*need,1,700),bid=cl(m*.7+value*.3,1,me.faab),max=cl(Math.max(bid,value*1.2),1,me.faab),ver=gain>=4?'ATTACK':gain>=2?'BID':bid<m*.55?'LET THEM SPEND':'PASS';return {pr,gain,m,bid,max,ver}}
function render(){let me=S.teams.find(t=>t.id===+S.me)||S.teams[0];if(!me)return;let rank=S.teams.findIndex(t=>t.id===me.id)+1,med=median(S.teams.map(t=>t.faab));$('week').textContent=`Week ${S.week}`;$('teamName').textContent=me.name;$('rank').textContent=`${rank}/${S.teams.length}`;$('proj').textContent=me.proj.toFixed(1);$('cut').textContent=S.cut.toFixed(1);$('risk').textContent=pc(me.risk);$('faab').textContent=usd(me.faab);$('median').textContent=usd(med);let mode=me.risk>=.18?'SURVIVAL MODE':me.risk<.08?'PRESERVE MODE':'SELECTIVE MODE';$('strategy').innerHTML=`<b>${mode}</b> • ${S.teams.length} teams alive • ${me.faab>=med?usd(me.faab-med)+' above':usd(med-me.faab)+' below'} league-median FAAB. ${mode==='PRESERVE MODE'?'Protect the bankroll; buy only cheap upgrades.':mode==='SURVIVAL MODE'?'Spend for meaningful starter points; survival outweighs future FAAB.':'Target clear upgrades without paying the early-season tax.'}`;
$('ranks').innerHTML=S.teams.map((t,i)=>{let s=t.proj-S.cut;return `<tr class="${t.id===me.id?'me':''}"><td><b>${i+1}</b></td><td><b>${t.name}</b></td><td class=num>${t.proj.toFixed(1)}</td><td class="num ${s<4?'bad':s<10?'warn':'good'}">${s>=0?'+':''}${s.toFixed(1)}</td><td class=num>${pc(t.risk)}</td><td class=num>${usd(t.faab)}</td></tr>`}).join('');
let danger=[...S.teams].sort((a,b)=>b.risk-a.risk).slice(0,5);$('watch').innerHTML=danger.map(t=>{let stars=(t.r.players||[]).map(id=>[id,points(id)]).sort((a,b)=>b[1]-a[1]).slice(0,5);return `<div style="padding:12px 0;border-bottom:1px solid var(--line)"><div style="display:flex;justify-content:space-between"><b>${t.name}</b><b>${pc(t.risk)}</b></div><div class=tiny style="margin-top:5px">If chopped: ${stars.map(x=>`${pname(x[0])} ${x[1].toFixed(1)}`).join(' • ')}</div></div>`}).join('');
let rostered=new Set(S.rosters.flatMap(r=>r.players||[]).map(String));let c=Object.keys(S.proj).filter(id=>!rostered.has(String(id))&&['QB','RB','WR','TE'].includes(ppos(id))&&points(id)>=4).map(id=>({id,...rec(id,me)})).sort((a,b)=>b.bid-a.bid).slice(0,35);$('bids').innerHTML=c.map(x=>`<tr><td><b>${pname(x.id)}</b><div class=tiny>${S.players[x.id]?.team||'FA'}</div></td><td>${ppos(x.id)}</td><td class=num>${x.pr.toFixed(1)}</td><td class=num>+${x.gain.toFixed(1)}</td><td class=num>${usd(x.m)}</td><td class=num><b>${usd(x.bid)}</b></td><td class=num>${usd(x.max)}</td><td><b>${x.ver}</b></td></tr>`).join('')||'<tr><td colspan=8>No projected free agents available.</td></tr>';
let h=paidBids().sort((a,b)=>b.week-a.week||b.bid-a.bid);$('history').innerHTML=h.slice(0,100).map(x=>`<tr><td>${x.week}</td><td>${pname(x.pid)}</td><td>${S.teams.find(t=>t.id===x.rid)?.name||'Roster '+x.rid}</td><td class=num>${usd(x.bid)}</td></tr>`).join('')||'<tr><td colspan=4>No paid waiver history yet. This section will begin learning automatically after the first waiver run.</td></tr>';$('agg').textContent=h.length?`Learning from ${h.length} paid bids • market x${leagueInflation().toFixed(2)}`:'Historical-market baseline';}
async function load(){try{$('status').textContent='Refreshing…';$('err').innerHTML='';let [league,users,rosters,state,players]=await Promise.all([get(`${A}/league/${L}`),get(`${A}/league/${L}/users`),get(`${A}/league/${L}/rosters`),get(`${A}/state/nfl`),get(`${A}/players/nfl`)]);S={league,users,rosters,state,players,week:num(state.week||state.display_week||1)};let season=league.season||state.season||2026;let raw=await get(`${PX}/${season}/${S.week}`);S.proj=raw||{};let tx=await Promise.all(Array.from({length:Math.max(1,S.week)},(_,i)=>get(`${A}/league/${L}/transactions/${i+1}`).catch(()=>[])));S.tx=tx.flat();S.teams=rosters.filter(r=>r.owner_id&&(r.players||[]).length).map(r=>({id:r.roster_id,name:teamName(r),r,faab:faabLeft(r),proj:bestLineup(r.players).total,risk:0}));if(!S.teams.length)throw new Error('No active rosters returned');let realProj=Object.keys(S.proj).filter(id=>pstats(id).pts_ppr!=null||pstats(id).pass_yd!=null||pstats(id).rush_yd!=null||pstats(id).rec_yd!=null).length;if(realProj<50)throw new Error(`Projection feed returned only ${realProj} usable weekly rows`);let sim=simulate(S.teams);S.cut=sim.cut;S.teams.forEach(t=>t.risk=(sim.chop.get(t.id)||0)/sim.n);S.teams.sort((a,b)=>b.proj-a.proj);let saved=+localStorage.getItem(`chopper_me_${L}`);S.me=S.teams.some(t=>t.id===saved)?saved:S.teams[0].id;$('me').innerHTML=S.teams.map(t=>`<option value=${t.id} ${t.id===S.me?'selected':''}>${t.name}</option>`).join('');$('diag').innerHTML=`<b>LIVE VALIDATION PASSED</b> • ${league.name} • ${S.teams.length} active rosters • ${realProj} usable Week ${S.week} projection rows • custom Sleeper scoring loaded • FAAB/transactions loaded • 8,000 survival simulations.`;$('status').textContent='Live • '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});render()}catch(e){console.error(e);$('err').innerHTML=`<div class=error><b>Live validation failed:</b> ${e.message}</div>`;$('diag').innerHTML='<b>VALIDATION BLOCKED</b> • The dashboard will not certify projections until the live feed is usable.';$('status').textContent='Load failed'}}
$('me').onchange=e=>{S.me=+e.target.value;localStorage.setItem(`chopper_me_${L}`,S.me);render()};$('refresh').onclick=load;load();setInterval(load,300000);